spring:
  profiles:
    active: ${ENV}
  application:
    name: Limpacity - Worker
  datasource:
    hikari:
      minimum-idle: ${minimum-idle:5}
      idle-timeout: ${idle-timeout:10000}
      connectionTimeout: ${idle-timeout:10000}
      poolName: SpringBootJPAHikariCP
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    show-sql: ${LOG_SQL:true}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql: true
        dialect: org.hibernate.dialect.MySQL55Dialect
        proc:
          param_null_passing:true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      javax:
        persistence.query.timeout: ${QUERY_TIMEOUT:10000}
        persistence.lock.timeout: ${LOCK_TIMEOUT:3000}
  batch:
    limit-thread: ${SPRING_BATCH_LIMIT:1}
    initialize-schema: never
    job:
      enabled: false          
    chunk: ${SPRING_BATCH_CHUNK}
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

limpacity:
  producerUrl: ${PRODUCER_URL:http://localhost:9002/producer/api/v1}
  producerToken: ${PRODUCER_TOKEN:''}

api:
  timeout: ${API_TIMEOUT:20000}

notificacoes:
  not1: ${NOT1:3}
  not2: ${NOT2:3}
  not3: ${NOT3:3}
  not4: ${NOT4:3}
  not5: ${NOT5:3}


info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

worker:
  scheduled.fixedRate: ${SCHEDULE_TIME}
  retry.maxtime: ${RETRY_MAX_TIME}
  
management.endpoint.health.show-details: always

timezone: ${TIMEZONE:America/Sao_Paulo}