spring:
  profiles:
    active: ${ENV}
  application:
    name: Limpacity - Worker
  datasource:
    hikari:
      minimum-idle: ${minimum-idle:5}
      idle-timeout: ${idle-timeout:10000}
      connectionTimeout: ${idle-timeout:10000}
      poolName: SpringBootJPAHikariCP
    url: jdbc:mysql://${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    limit-thread: ${SPRING_BATCH_LIMIT:1}
    initialize-schema: never
    job:
      enabled: false          
    chunk: ${SPRING_BATCH_CHUNK}
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

info:
  app:
    encoding: '@project.build.sourceEncoding@'
  java:
    source: '@java.version@'
    target: '@java.version@'
  build:
    artifact: '@project.artifactId@'
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

worker:
  scheduled.fixedRate: ${SCHEDULE_TIME}
  retry.maxtime: ${RETRY_MAX_TIME}
  
management.endpoint.health.show-details: always

